### ISSUE TITLE
Getting logs for a pending task fails

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#286]
### How to Reproduce

- Start instance that requires download of Docker image
- While image is downloading, the task allocation is pending, click on stdout log
- ???
- Receive error message:

![image](https://user-images.githubusercontent.com/3427394/29615277-91bc22a2-880d-11e7-8e53-40e328398ec7.png)

```
play.api.UnexpectedException: Unexpected exception[UnexpectedNomadHttpApiError: Unexpected Nomad response: 500 Internal Server Error]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1$$anonfun$apply$6.apply(Future.scala:346)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:44)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:252)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:157)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: de.frosner.broccoli.nomad.UnexpectedNomadHttpApiError: Unexpected Nomad response: 500 Internal Server Error
	at de.frosner.broccoli.nomad.NomadHttpClient.de$frosner$broccoli$nomad$NomadHttpClient$$toError(NomadHttpClient.scala:125)
	at de.frosner.broccoli.nomad.NomadHttpClient$$anonfun$getTaskLog$1$$anonfun$apply$5$$anonfun$apply$8.apply(NomadHttpClient.scala:119)
	at de.frosner.broccoli.nomad.NomadHttpClient$$anonfun$getTaskLog$1$$anonfun$apply$5$$anonfun$apply$8.apply(NomadHttpClient.scala:119)
	at cats.syntax.EitherOps$.ensureOr$extension(either.scala:85)
	at cats.data.EitherT$$anonfun$ensureOr$1.apply(EitherT.scala:59)
	at cats.data.EitherT$$anonfun$ensureOr$1.apply(EitherT.scala:59)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Expected Behaviour

The log button should not be enabled if nothing can be downloaded and if you anyway go to the URL there should be a 404.

**Comment by swsnr** [comment]
@FRosner Did you check what exception is thrown?  

I agree that there should be a 404 or an empty log while there are no logs, but it's hard, if not impossible, to disable the buttons—we don't know that there are no logs until we try to access the logs…

**Comment by FRosner** [comment]
Does it make sense to disable if the task is not running? Is there a way to see non-running tasks and wanting to get logs from the UI?

**Comment by swsnr** [comment]
@FRosner Do logs only ever come from running tasks?  What about pending tasks?

**Comment by FRosner** [comment]
I'm not sure. I have never gotten any logs from pending tasks. But tbh if we don't disable it but show 404 it's good enough. In the end people will refresh the page and that's ok.

So for me it's fine to keep it enabled just to avoid that there might be logs but you can't click but then don't throw an exception.

**Comment by swsnr** [comment]
So, what exception was it?  Do you have those logs?

**Comment by FRosner** [comment]
I had updated the initial description, sorry. Nomad returned a 500.

**Comment by FRosner** [comment]
I checked and it seems that Nomad returns 500 when anything is wrong. This was tested on Nomad 0.5.6.

```
curl -v localhost:4646/v1/client/fs/logs/43432
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 4646 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4646 (#0)
> GET /v1/client/fs/logs/43432 HTTP/1.1
> Host: localhost:4646
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Vary: Accept-Encoding
< Date: Wed, 23 Aug 2017 13:58:23 GMT
< Content-Length: 22
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
must provide task name%
```

```
curl -v 'localhost:4646/v1/client/fs/logs/43432?task=4233'
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 4646 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4646 (#0)
> GET /v1/client/fs/logs/43432?task=4233 HTTP/1.1
> Host: localhost:4646
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Vary: Accept-Encoding
< Date: Wed, 23 Aug 2017 13:59:11 GMT
< Content-Length: 37
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
must provide log type (stdout/stderr)
```

```
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 4646 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4646 (#0)
> GET /v1/client/fs/logs/43432?task=4233&type=stderr HTTP/1.1
> Host: localhost:4646
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Vary: Accept-Encoding
< Date: Wed, 23 Aug 2017 13:59:26 GMT
< Content-Length: 29
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host localhost left intact
unknown allocation ID "43432"
```

The back-end just logs an ERR statement.
