### ISSUE TITLE
[error] error Command failed with exit code 2.

### ISSUE THREAD

**Issue by pravicloud** [FRosner/cluster-broccoli#373]
Hi Team,

Please check this issue. while try to build the broccoli i am getting the below error message.
 

[error] error Command failed with exit code 2.
[info] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
java.lang.AssertionError: assertion failed: Nonzero exit value '2', while executing: /home/ansadmin/cluster-broccoli/webui> yarn dist -- --output-path /home/ansadmin/cluster-broccoli/webui/target/scala-2.11/resource_managed/main/public
        at scala.Predef$.assert(Predef.scala:179)
        at YarnPlugin$.YarnPlugin$$execute(YarnPlugin.scala:134)
        at YarnPlugin$$anonfun$projectSettings$6$$anonfun$3.apply(YarnPlugin.scala:106)
        at YarnPlugin$$anonfun$projectSettings$6$$anonfun$3.apply(YarnPlugin.scala:101)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at YarnPlugin$$anonfun$projectSettings$6.apply(YarnPlugin.scala:118)
        at YarnPlugin$$anonfun$projectSettings$6.apply(YarnPlugin.scala:91)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (webui/*:yarnDist) java.lang.AssertionError: assertion failed: Nonzero exit value '2', while executing: /home/ansadmin/cluster-broccoli/webui> yarn dist -- --output-path /home/ansadmin/cluster-broccoli/webui/target/scala-2.11/resource_managed/main/public
[error] Total time: 43 s, completed Oct 4, 2019 9:05:43 AM

**Comment by sohaibiftikhar** [comment]
Can you give me the output of `node -v` you are running? This is a known issue. Node version cannot be newer than `v10.9.0`

**Comment by pravicloud** [comment]
node -v
v10.16.3

which version do i need to use? could please tell me the version need to use in Linux

**Comment by pravicloud** [comment]
Hi Sohaib,

It's working now.

Thank you very much
