### ISSUE TITLE
Improve error message when running against an empty templates dir

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#54]
```
[error] a.a.OneForOneStrategy - Unable to provision, see the following errors:

1) Error injecting constructor, java.util.NoSuchElementException: None.get
  at de.frosner.broccoli.services.InstanceService.<init>(InstanceService.scala:21)
  at de.frosner.broccoli.services.InstanceService.class(InstanceService.scala:21)
  while locating de.frosner.broccoli.services.InstanceService

1 error
akka.actor.ActorInitializationException: exception during creation
    at akka.actor.ActorInitializationException$.apply(Actor.scala:166) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.actor.ActorCell.create(ActorCell.scala:596) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.10.6.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [org.scala-lang.scala-library-2.10.6.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.10.6.jar:na]
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.util.NoSuchElementException: None.get
  at de.frosner.broccoli.services.InstanceService.<init>(InstanceService.scala:21)
  at de.frosner.broccoli.services.InstanceService.class(InstanceService.scala:21)
  while locating de.frosner.broccoli.services.InstanceService

1 error
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[com.google.inject.guice-4.0.jar:na]
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[com.google.inject.guice-4.0.jar:na]
    at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[com.typesafe.play.play_2.10-2.4.6.jar:2.4.6]
    at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[com.typesafe.play.play_2.10-2.4.6.jar:2.4.6]
    at play.api.libs.concurrent.ActorRefProvider$$anonfun$1.apply(Akka.scala:209) ~[com.typesafe.play.play_2.10-2.4.6.jar:2.4.6]
    at play.api.libs.concurrent.ActorRefProvider$$anonfun$1.apply(Akka.scala:209) ~[com.typesafe.play.play_2.10-2.4.6.jar:2.4.6]
    at akka.actor.TypedCreatorFunctionConsumer.produce(Props.scala:346) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.actor.Props.newActor(Props.scala:255) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.actor.ActorCell.newActor(ActorCell.scala:552) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
    at akka.actor.ActorCell.create(ActorCell.scala:578) ~[com.typesafe.akka.akka-actor_2.10-2.3.13.jar:na]
Caused by: java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:313) ~[org.scala-lang.scala-library-2.10.6.jar:na]
    at scala.None$.get(Option.scala:311) ~[org.scala-lang.scala-library-2.10.6.jar:na]
    at de.frosner.broccoli.services.InstanceService.<init>(InstanceService.scala:42) ~[cluster-broccoli.cluster-broccoli-0.1.0-SNAPSHOT-sans-externalized.jar:na]
    at de.frosner.broccoli.services.InstanceService$$FastClassByGuice$$d986dc01.newInstance(<generated>) ~[com.google.inject.guice-4.0.jar:na]
    at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[com.google.inject.guice-4.0.jar:na]
    at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) ~[com.google.inject.guice-4.0.jar:na]
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105) ~[com.google.inject.guice-4.0.jar:na]
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[com.google.inject.guice-4.0.jar:na]
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[com.google.inject.guice-4.0.jar:na]
    at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[com.google.inject.guice-4.0.jar:na]
```

**Comment by FRosner** [comment]
Is not reproducible. I forgot to pull and used a very old version of the image.
