### ISSUE TITLE
Better error message for invalid options

### ISSUE THREAD

**Issue by omame** [FRosner/cluster-broccoli#81]
When a user starts the app with an invalid option (in my case I forgot to add `http://` before the nomad url) this is what gets reported:

```
[error] a.a.OneForOneStrategy - scheme
java.lang.NullPointerException: scheme
        at com.ning.http.client.uri.Uri.<init>(Uri.java:56) ~[com.ning.async-http-client-1.9.21.jar:na]
        at com.ning.http.client.uri.Uri.create(Uri.java:32) ~[com.ning.async-http-client-1.9.21.jar:na]
        at com.ning.http.client.uri.Uri.create(Uri.java:25) ~[com.ning.async-http-client-1.9.21.jar:na]
        at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.java:307) ~[com.ning.async-http-client-1.9.21.jar:na]
        at com.ning.http.client.RequestBuilder.setUrl(RequestBuilder.java:165) ~[com.ning.async-http-client-1.9.21.jar:na]
        at play.api.libs.ws.ning.NingWSRequest.buildRequest(NingWS.scala:218) ~[com.typesafe.play.play-ws_2.10-2.4.6.jar:2.4.6]
        at play.api.libs.ws.ning.NingWSRequest.execute(NingWS.scala:128) ~[com.typesafe.play.play-ws_2.10-2.4.6.jar:2.4.6]
        at play.api.libs.ws.WSRequest$class.get(WS.scala:408) ~[com.typesafe.play.play-ws_2.10-2.4.6.jar:2.4.6]
        at play.api.libs.ws.ning.NingWSRequest.get(NingWS.scala:81) ~[com.typesafe.play.play-ws_2.10-2.4.6.jar:2.4.6]
        at de.frosner.broccoli.services.NomadService.de$frosner$broccoli$services$NomadService$$executeGetStatuses(NomadService.scala:38) ~[cluster-broccoli.cluster-broccoli-0.4.0-SNAPSHOT-sans-externalized.jar:na]
```

Clearly, this isn't very helpful and it's impossible to guess what the issue is.
Options should be sanitised and the app should log a useful error message and refuse to start.

**Comment by FRosner** [comment]
Thanks for reporting this @omame!
